config/routes.rb
Rails.application.routes.draw do
  root :to => "sessions#new"

  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users do
    resources :questions
  end

  resources :questions do
    resources :responses
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, :presence => true
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :content, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :responses

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  validates_uniqueness_of :email

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Successfully Updated!"
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js
      end
    else
      render:edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "Question Removed"
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js
      end
    else
      flash[:alert] = "Horrible failure"
      redirect_to questions_path
    end
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @response = Response.new
    @responses = @question.responses
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = "Question submitted!"
      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js
      end
    else
      flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  private
    def question_params
      params.require(:question)
            .permit(:title, :body, :user_id)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
  end

  def destroy
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
    if @response.destroy
      flash[:notice] = "Response Removed"
      respond_to do |format|
        format.html { redirect_to question_path(@question) }
        format.js
      end
    else
      flash[:alert] = "Something Went Horribly Wrong"
      redirect_to questions_path
    end
  end

  def create
    @question = Question.find(params[:question_id])
    @response = Response.new(response_params)
    @response.user_id = current_user.id
    @response.question_id = @question.id
    if @response.save
      flash[:notice] = "Thanks for answering!"
      respond_to do |format|
        format.html { redirect_to question_path(@question) }
        format.js
      end
    else
      flash[:alert] = "Something went Wrong!"
      redirect_to questions_path
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
    if @response.update(response_params)
      flash[:notice] = "Successfully Updated"
      redirect_to question_path(@question)
    else
      flash[:alert] = "Something Went Wrong"
      redirect_to question_path(@question)
    end
  end


private
  def response_params
    params.require(:response)
      .permit(:content, :user_id, :question_id, :best?, :score)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "Login successful!"
      session[:user_id] = @user.id
      redirect_to questions_path()
    else
      flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Log out successful"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      flash[:notice] = "Success! Please log in below"
      redirect_to root_path
    else
      flash[:alert] = "There was a problem!"
      render :new
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors.</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <h1>Yak Overflow!</h1>
      <div class="navbar-text navbar-left">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home ", questions_path %></li>
          <li><%= link_to " Log out", log_out_path %></li>
        </ul>
      </div>
    </div>
      <p class="navbar-text navbar-right">Signed in as <%= current_user.email %></p>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YakOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/questions/_question.html.erb
  <li id="shown_question_<%= question.id %>"><%= link_to question.title, question_path(question) %>
    <% if question.user_id == current_user.id %>
       |
       <%= link_to "Edit", edit_question_path(question), remote: true %>
       |
       <%= link_to "Delete", question_path(question),
                  :data => {:confirm => "Are you sure?",
                            :method => "delete"}%>
    <% end %>


  </li>

app/views/questions/create.js.erb
$('#question_title').val('');
$('#question_body').val('');
$('#questions').append('<%= j render(@question) %>');

app/views/questions/destroy.js.erb
$('#shown_question_<%= @question.id %>').remove();

app/views/questions/edit.html.erb
<h1>Edit your Question!</h1>

<%= render "form" %>

app/views/questions/edit.js.erb
$('#shown_question_<%= @question.id %>').after('<span class="edit_form"><%= j render "form" %></span>')
$('#shown_question_<%= @question.id %>').remove();
$('#new_form').hide();

app/views/questions/index.html.erb
<%= render 'layouts/navbar' %>

<h1>Hello <%= current_user.email %>!</h1>

<ul id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
  <% end %>
</ul>

<div id="new_form">
  <h2>Ask a new question:</h2>
  <%= render 'form' %>
</div>

app/views/questions/show.html.erb
<%= render 'layouts/navbar' %>

<h1><%= @question.title %></h1>

<p>
  <%= @question.body %>
</p>



  <ul id="responses">
  <% @responses.each do |response| %>
    <%= render response %>
  <% end %>
  </ul>


<div id="new_response_form">
  <h4>Respond to this question:</h4>
  <%= render 'responses/form' %>
</div>

app/views/questions/update.js.erb
$('.edit_form').after('<%= j render(@question) %>');
$('.edit_form').remove();
$('#new_form').show();

app/views/responses/_form.html.erb
<%= form_for [@question, @response], remote: true do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/responses/_response.html.erb
<li id="shown_response_<%= response.id %>">
  <%= response.content %>
  <% if response.user_id == current_user.id %>
   |
  <%= link_to "Edit", edit_question_response_path(@question, response), remote: true %>
   |
   <%= link_to "Delete", question_response_path(@question, response),
                :data => {:confirm => "oh NOOOOO",
                          :method => "delete"}%>
  <% end %>
</li>

app/views/responses/create.js.erb
$('#response_content').val('');
$('#responses').append('<%= j render(@response) %>');

app/views/responses/edit.html.erb
<h4>Edit response</h4>
<%= render "form" %>

app/views/responses/edit.js.erb
$('#shown_response_<%= @response.id %>').after('<span class="edit_form"><%= j render "form" %></span>')
$('#shown_response_<%= @response.id %>').remove();
$('#new_response_form').hide();

app/views/responses/new.html.erb
<%= render "form" %>

app/views/users/_form.html.erb
<h3>Log in</h3>

<%= render 'layouts/errors', :object => @user %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create Account", class: 'btn btn-info' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign in</h1>

<%= render "form" %>

<p><%= link_to "Go back to login page", root_path %></p>